# Conversion to YAML from Properties formar report
# Warnings:
# - The yaml file had comments which are lost in the refactoring!
spring:
  application:
    name: JRTP-ApplicationRegistrationService
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///jrtp-ish-db
    username: root
    password: 757052
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 7071
ar:
  ssa-web:
    url: http://localhost:9090/ssa-web-api/find/{ssn}
  state: California

