server:
  port: 7073
spring:
  application:
    name: JRTP-ElgibilityDeterminationService
  config:
    import: optional:configserver:http://localhost:8888
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql:///jrtp-ish-db
#    username: root
#    password: 757052
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    show-sql: true
#    hibernate:
#      ddl-auto: update
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
