server:
  port: 7076
spring:
  application:
    name: JRTP-(BI)BenefitInsuranceAPI
  config:
    import: optional:configserver:http://localhost:8888
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql:///jrtp-ish-db
#    username: root
#    password: 757052
#  jpa:
#    show-sql: true
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    hibernate:
#      ddl-auto: update
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka